services:
  - type: web
    name: gestion-stock
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false  # à remplir manuellement dans Render avec l'URL PostgreSQL
